export const errorAutentication = {
    "auth/admin-restricted-operation": "Operación restringida a administradores.",
    "auth/argument-error": "Error en los argumentos proporcionados.",
    "auth/app-not-authorized": "La aplicación no está autorizada para usar Firebase Authentication.",
    "auth/app-not-installed": "La aplicación no está instalada en el dispositivo.",
    "auth/captcha-check-failed": "La verificación del CAPTCHA falló.",
    "auth/code-expired": "El código ha expirado.",
    "auth/cordova-not-ready": "Cordova no está listo.",
    "auth/cors-unsupported": "El navegador no soporta CORS.",
    "auth/credential-already-in-use": "Las credenciales ya están en uso por otra cuenta.",
    "auth/custom-token-mismatch": "El token personalizado no coincide.",
    "auth/requires-recent-login": "Es necesario volver a iniciar sesión.",
    "auth/dependent-sdk-initialized-before-auth": "El SDK dependiente se inicializó antes de la autenticación.",
    "auth/dynamic-link-not-activated": "El enlace dinámico no está activado.",
    "auth/email-change-needs-verification": "El cambio de correo electrónico requiere verificación.",
    "auth/email-already-in-use": "El correo electrónico ya está en uso.",
    "auth/emulator-config-failed": "Error en la configuración del emulador.",
    "auth/expired-action-code": "El código de acción ha expirado.",
    "auth/cancelled-popup-request": "La solicitud de la ventana emergente fue cancelada.",
    "auth/internal-error": "Error interno del servidor.",
    "auth/invalid-api-key": "La clave de API es inválida.",
    "auth/invalid-app-credential": "Las credenciales de la aplicación son inválidas.",
    "auth/invalid-app-id": "El ID de la aplicación es inválido.",
    "auth/invalid-user-token": "El token del usuario es inválido.",
    "auth/invalid-auth-event": "El evento de autenticación es inválido.",
    "auth/invalid-cert-hash": "El hash del certificado es inválido.",
    "auth/invalid-verification-code": "El código de verificación es inválido.",
    "auth/invalid-continue-uri": "La URI de continuación es inválida.",
    "auth/invalid-cordova-configuration": "La configuración de Cordova es inválida.",
    "auth/invalid-custom-token": "El token personalizado es inválido.",
    "auth/invalid-dynamic-link-domain": "El dominio del enlace dinámico es inválido.",
    "auth/invalid-email": "El correo electrónico es inválido.",
    "auth/invalid-emulator-scheme": "El esquema del emulador es inválido.",
    "auth/invalid-credential": "Las credenciales son inválidas.",
    "auth/invalid-message-payload": "El contenido del mensaje es inválido.",
    "auth/invalid-multi-factor-session": "La sesión de autenticación multifactor es inválida.",
    "auth/invalid-oauth-client-id": "El ID del cliente OAuth es inválido.",
    "auth/invalid-oauth-provider": "El proveedor OAuth es inválido.",
    "auth/invalid-action-code": "El código de acción es inválido.",
    "auth/unauthorized-domain": "El dominio no está autorizado.",
    "auth/wrong-password": "La contraseña es incorrecta.",
    "auth/invalid-persistence-type": "El tipo de persistencia es inválido.",
    "auth/invalid-phone-number": "El número de teléfono es inválido.",
    "auth/invalid-provider-id": "El ID del proveedor es inválido.",
    "auth/invalid-recipient-email": "El correo electrónico del destinatario es inválido.",
    "auth/invalid-sender": "El remitente es inválido.",
    "auth/invalid-verification-id": "El ID de verificación es inválido.",
    "auth/invalid-tenant-id": "El ID del arrendatario es inválido.",
    "auth/multi-factor-info-not-found": "La información del factor multifactor no se encontró.",
    "auth/multi-factor-auth-required": "Se requiere autenticación multifactor.",
    "auth/missing-android-pkg-name": "Falta el nombre del paquete Android.",
    "auth/missing-app-credential": "Faltan las credenciales de la aplicación.",
    "auth/auth-domain-config-required": "Es necesario configurar el dominio de autenticación.",
    "auth/missing-verification-code": "Falta el código de verificación.",
    "auth/missing-continue-uri": "Falta la URI de continuación.",
    "auth/missing-iframe-start": "Falta el inicio del iframe.",
    "auth/missing-ios-bundle-id": "Falta el ID del paquete iOS.",
    "auth/missing-or-invalid-nonce": "Falta o es inválido el nonce.",
    "auth/missing-multi-factor-info": "Falta la información del factor multifactor.",
    "auth/missing-multi-factor-session": "Falta la sesión de autenticación multifactor.",
    "auth/missing-phone-number": "Falta el número de teléfono.",
    "auth/missing-verification-id": "Falta el ID de verificación.",
    "auth/app-deleted": "La aplicación fue eliminada.",
    "auth/account-exists-with-different-credential": "La cuenta ya existe con diferentes credenciales.",
    "auth/network-request-failed": "La solicitud de red falló.",
    "auth/null-user": "El usuario es nulo.",
    "auth/no-auth-event": "No hay evento de autenticación.",
    "auth/no-such-provider": "No existe tal proveedor.",
    "auth/operation-not-allowed": "Operación no permitida.",
    "auth/operation-not-supported-in-this-environment": "Operación no soportada en este entorno.",
    "auth/popup-blocked": "La ventana emergente fue bloqueada.",
    "auth/popup-closed-by-user": "La ventana emergente fue cerrada por el usuario.",
    "auth/provider-already-linked": "El proveedor ya está vinculado a la cuenta.",
    "auth/quota-exceeded": "Se ha superado la cuota.",
    "auth/redirect-cancelled-by-user": "La redirección fue cancelada por el usuario.",
    "auth/redirect-operation-pending": "Operación de redirección pendiente.",
    "auth/rejected-credential": "Credenciales rechazadas.",
    "auth/second-factor-already-in-use": "El segundo factor ya está en uso.",
    "auth/maximum-second-factor-count-exceeded": "Se ha superado el número máximo de factores secundarios.",
    "auth/tenant-id-mismatch": "El ID del arrendatario no coincide.",
    "auth/timeout": "Tiempo de espera agotado.",
    "auth/user-token-expired": "El token del usuario ha expirado.",
    "auth/too-many-requests": "Demasiados intentos. Inténtalo más tarde.",
    "auth/unauthorized-continue-uri": "URI de continuación no autorizada.",
    "auth/unsupported-first-factor": "Primer factor no soportado.",
    "auth/unsupported-persistence-type": "Tipo de persistencia no soportado.",
    "auth/unsupported-tenant-operation": "Operación no soportada para este arrendatario.",
    "auth/unverified-email": "Correo electrónico no verificado.",
    "auth/user-cancelled": "El usuario canceló la operación.",
    "auth/user-not-found": "Usuario no encontrado.",
    "auth/user-disabled": "El usuario está deshabilitado.",
    "auth/user-mismatch": "El usuario no coincide.",
    "auth/user-signed-out": "El usuario cerró sesión.",
    "auth/weak-password": "La contraseña es demasiado débil.",
    "auth/web-storage-unsupported": "El almacenamiento web no es compatible.",
    "auth/already-initialized": "Firebase ya está inicializado."
};